name: Push to main
env:
  main_project_module: Lap Tracks
  playstore_name: Lap Tracks
on:
  workflow_dispatch:

  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Setup Jdk
        uses: actions/setup-java@v4.0.0
        with:
          distribution: "adopt"
          java-version: "18"

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      # Run test suite in project
      - name: Run gradle tests
        run: ./gradlew test

      # Build Project
      - name: Build gradle
        run: ./gradlew build

      # Create APK Debug
      - name: Build apk debug project (APK) - ${{ env.main_project_module }} module
        run: ./gradlew assembleDebug

      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.SERVICECREDENTIALSFILECONTENT }}
          groups: testers
          file: app/build/outputs/apk/debug/app-debug.apk
        #TODO: Add release notes.